### ISSUE TITLE
Have you solved this problem, can you public the modified code?

### ISSUE THREAD

**Issue by xausky** [lrahmani/snipet-routed-host-bootstrap#1]
Look here you seem to have solved it, thanks.

https://github.com/libp2p/go-libp2p-kad-dht/issues/645

**Comment by xausky** [comment]
I found the place to modify, thanks

**Comment by wenzhang945** [comment]
@xausky  Do you have fixed the issue now? I also follow the way lrahmani mentioned but i still faced the issue "failed to find any peer in table" for my local environment.  

code snippet of dht.go:
func NewDHT(ctx context.Context, h host.Host, dstore ds.Batching) *IpfsDHT {
	dht, err := New(ctx, h, Datastore(dstore), Mode(ModeServer), ProtocolPrefix("/test_app/kad/1.0.0"))

Could you give some suggestions? Thanks!



Regards,
Andy

**Comment by xausky** [comment]
@wenzhang945  I just made the following modifications and it works for node.go

	- ndht := dht.NewDHT(ctx, basicHost, dstore)
	+ ndht, err := dht.New(ctx, basicHost, dht.Datastore(dstore), dht.Mode(dht.ModeServer))
	+ if err != nil {
	+ 	return nil, nil, err
	+ }

**Comment by wenzhang945** [comment]
Hey xausky,

Ok, thanks for quick reply!   I also have some questions below, could you have a look? thanks!
1. how about public DHT case, Is the second node also ok for you?  If so, do you make some configration changes for ipfs?
2. What's the version of ipfs you used?

Regards,
Andy

**Comment by xausky** [comment]
@wenzhang945 I have no changes to ipfs, I have tried the version go-libp2p v0.8.3 in this repository or my own project go-libp2p v0.17.0 and it all works fine, this option should be turned off when publishing on the public network. 我啥都没改，go-libp2p v0.8.3 和 v0.17.0 都可以用，加上那个 dht.Mode(dht.ModeServer) 参数就行。

**Comment by wenzhang945** [comment]
好的，谢谢
